import json
import sqlite3
from pathlib import Path

import numpy as np
import pytest

from sim.dynamics.orbit.cr3bp import cr3bp_halo_seed_state_km_s, propagate_cr3bp_state
from sim.review.cr3bp import STATE_COLUMNS, load_cr3bp_history, render_cr3bp_research
from sim.review.workspace import ReviewWorkspace


@pytest.fixture
def workspace(tmp_path):
    review = tmp_path / "review"
    review.mkdir()
    db = review / "run.sqlite"
    with sqlite3.connect(db) as conn:
        conn.execute("CREATE TABLE object_state_frame (object_id TEXT, state_frame TEXT)")
        conn.execute("INSERT INTO object_state_frame VALUES ('vehicle', 'cr3bp_rotating')")
        conn.execute("CREATE TABLE object_propagation (object_id TEXT, propagator_family TEXT, propagator_name TEXT)")
        conn.execute("INSERT INTO object_propagation VALUES ('vehicle', 'CR3BP', 'earth_moon CR3BP')")
        conn.execute(
            "CREATE TABLE object_state (object_id TEXT, time_s REAL, "
            + ", ".join(c + " REAL" for c in STATE_COLUMNS)
            + ")"
        )
        state = cr3bp_halo_seed_state_km_s(family="l1_northern_large")
        for t in np.arange(0.0, 7200.0, 300.0):
            conn.execute("INSERT INTO object_state VALUES (?, ?, ?, ?, ?, ?, ?, ?)", ["vehicle", t, *state])
            state = propagate_cr3bp_state(state, 300.0, t)
    with ReviewWorkspace.open(tmp_path) as opened:
        yield opened


@pytest.mark.parametrize("kind", ["trajectory", "zero_velocity", "jacobi"])
def test_research_figures_and_receipts(workspace, kind):
    result = render_cr3bp_research(workspace, "vehicle", kind=kind, resolution=31)
    receipt = json.loads(Path(result["receipt"]).read_text())
    assert receipt["review_store"]["sha256"] == workspace.evidence_identity()["sha256"]
    assert receipt["query_parameters"] == ["vehicle"]
    assert receipt["system"]["name"] == "earth_moon"
    assert receipt["visual_qa_status"] == "pending_agent_review"
    assert (workspace.review_dir / "generated_artifacts.json").is_file()


def test_movie_timing_and_contact_sheet(workspace):
    from PIL import Image

    result = render_cr3bp_research(
        workspace, "vehicle", axes="inertial", origin="p2", movie_format="gif", frames=6, fps=3
    )
    receipt = json.loads(Path(result["receipt"]).read_text())
    assert receipt["movie_frame_times_s"][0] == 0
    assert receipt["movie_frame_times_s"][-1] == 6900
    with Image.open(result["movie"]) as movie:
        assert movie.n_frames == 6
    with Image.open(result["contact_sheet"]) as sheet:
        assert sheet.width > 0 and sheet.height > 0
    assert receipt["movie_qa"]["automated_status"] == "passed"


@pytest.mark.parametrize("field,value", [("state_frame", "eci"), ("propagator_name", "sun_earth CR3BP")])
def test_reject_wrong_frame_or_system(workspace, field, value):
    with sqlite3.connect(workspace.db_path) as conn:
        table = "object_state_frame" if field == "state_frame" else "object_propagation"
        conn.execute(f"UPDATE {table} SET {field} = ?", [value])
    with pytest.raises(ValueError):
        load_cr3bp_history(workspace, "vehicle")


def test_reject_duplicate_times(workspace):
    with sqlite3.connect(workspace.db_path) as conn:
        conn.execute("UPDATE object_state SET time_s = 0")
    with pytest.raises(ValueError, match="increasing"):
        load_cr3bp_history(workspace, "vehicle")


def test_reject_inertial_zero_velocity(workspace):
    with pytest.raises(ValueError, match="rotating"):
        render_cr3bp_research(workspace, "vehicle", kind="zero_velocity", axes="inertial")


def test_contours_update_geometry_without_accumulating_artists():
    import matplotlib.pyplot as plt

    from sim.review.cr3bp import _ZeroVelocityContours

    u, v = np.meshgrid(np.linspace(-2, 2, 31), np.linspace(-2, 2, 31))
    fig, ax = plt.subplots()
    try:
        contours = _ZeroVelocityContours(ax, u, v, u)
        for c in [0.0, 1.0, -1.0, 1.0, 0.0]:
            contours.update(c)
            assert len(ax.collections) == 2
            line = contours.artists[1].get_paths()[0].vertices
            np.testing.assert_allclose(line[:, 0], c, atol=1e-14)
        contours.update(-3.0)  # Entire domain allowed; no zero contour.
        assert len(ax.collections) == 1
        contours.update(3.0)  # Entire domain forbidden.
        assert len(ax.collections) == 1
        contours.update(0.0)  # Contour reappears on rewind/contact-sheet selection.
        assert len(ax.collections) == 2
    finally:
        plt.close(fig)


@pytest.mark.parametrize("mode", ["fixed", "instantaneous"])
def test_maneuver_movie_uses_sample_jacobi(workspace, mode):
    from sim.dynamics.orbit.cr3bp_research import cr3bp_jacobi_constant
    from sim.review.cr3bp import load_cr3bp_history

    # This database is a synthetic test fixture, generated by OEL propagation.
    state = cr3bp_halo_seed_state_km_s(family="l1_northern_large")
    with sqlite3.connect(workspace.db_path) as conn:
        conn.execute("DELETE FROM object_state")
        for t in np.arange(0.0, 7201.0, 300.0):
            conn.execute("INSERT INTO object_state VALUES (?, ?, ?, ?, ?, ?, ?, ?)", ["vehicle", t, *state])
            accel = np.array([0.0, 5e-5, 0.0]) if 1800 <= t < 5400 else np.zeros(3)
            state = propagate_cr3bp_state(state, 300.0, t, accel, integrator="rkf78")
    times, states, system = load_cr3bp_history(workspace, "vehicle")
    c = cr3bp_jacobi_constant(states, system=system)
    assert np.ptp(c) > 0.01
    np.testing.assert_allclose(c[:7], c[0], atol=1e-12, rtol=0)
    np.testing.assert_allclose(c[18:], c[18], atol=1e-12, rtol=0)
    result = render_cr3bp_research(
        workspace,
        "vehicle",
        kind="zero_velocity",
        jacobi_mode=mode,
        movie_format="gif",
        frames=7,
        fps=3,
        resolution=61,
        bounds_km=(-600000, 600000, -600000, 600000),
    )
    receipt = json.loads(Path(result["receipt"]).read_text())
    indices = receipt["movie_sample_indices"]
    expected = c[indices] if mode == "instantaneous" else np.full(7, c[0])
    np.testing.assert_allclose(receipt["movie_jacobi_values"], expected)
    np.testing.assert_array_equal(receipt["movie_frame_times_s"], times[indices])
    assert receipt["movie_qa"]["automated_status"] == "passed"


@pytest.mark.parametrize(
    "kwargs",
    [
        {"kind": "trajectory", "movie_format": "gif"},
        {"kind": "zero_velocity"},
        {"kind": "zero_velocity", "movie_format": "gif", "jacobi": 3.1},
    ],
)
def test_reject_incompatible_instantaneous_modes(workspace, kwargs):
    with pytest.raises(ValueError, match="Instantaneous|conflicts"):
        render_cr3bp_research(workspace, "vehicle", jacobi_mode="instantaneous", **kwargs)
