import importlib

from sim.actuators import (
    ActuatorLimits,
    AttitudeActuator,
    MagnetorquerLimits,
    OrbitalActuator,
    OrbitalActuatorLimits,
    ReactionWheelLimits,
    SimpleActuator,
    ThrusterPulseLimits,
)
from sim.api import SimulationConfig, SimulationResult, SimulationSession, SimulationSnapshot
from sim.control import (
    AttitudeAgnosticImpulsiveManeuverer,
    DeltaVManeuver,
    DetumbleThenSlewController,
    ECIDetumblePDController,
    PoseCommandGenerator,
    IntegratedManeuverCommand,
    IntegratedManeuverDecision,
    HCWLQRController,
    HCWNoRadialLQRController,
    HCWNoRadialManualController,
    HCWCurvInputRectOutputController,
    HCWInTrackCrossTrackMPCController,
    RelativeOrbitMPCController,
    PredictiveBurnConfig,
    PredictiveBurnScheduler,
    OrbitalAttitudeManeuverCoordinator,
    ThrustLimitedDeltaVManeuver,
    ThrustLimitedDeltaVManeuverResult,
    ImpulsiveManeuver,
    ImpulsiveManeuverResult,
    QuaternionPDController,
    ReactionWheelPDController,
    ReactionWheelPIDController,
    RICDetumblePDController,
    RICFrameLQRController,
    RICFramePDController,
    RICFramePIDController,
    RiskThresholdController,
    RobustMPCController,
    SafetyBarrierController,
    SmallAngleLQRController,
    SnapAndHoldRICAttitudeController,
    SnapAttitudeController,
    SurrogateSnapECIController,
    SurrogateSnapRICController,
    StationkeepingController,
    StochasticPolicyController,
    ZeroController,
    ZeroTorqueController,
)
from sim.config import (
    AgentSection,
    AlgorithmPointer,
    BridgePointer,
    GroundStationSection,
    MonteCarloSection,
    MonteCarloVariation,
    OutputsSection,
    PROFILE_FAST,
    PROFILE_HIGH_FIDELITY,
    PROFILE_OPS,
    SimulatorSection,
    SimulationScenarioConfig,
    SimulationProfile,
    SimulationProfileName,
    build_default_ops_orbit_propagator,
    build_orbit_propagator_for_profile,
    default_disturbance_config_for_profile,
    default_env_for_profile,
    get_simulation_profile,
    load_simulation_yaml,
    profile_choices,
    resolve_dt_s,
    resolve_steps_for_duration,
    scenario_config_from_dict,
    validate_scenario_plugins,
)
from sim.core.models import Command, ObjectConfig, SimConfig, SimLog, SimObject, StateBelief, StateTruth
from sim.dynamics.attitude import DisturbanceTorqueConfig, DisturbanceTorqueModel
from sim.dynamics.model import OrbitalAttitudeDynamics
from sim.dynamics.orbit import (
    AtmosphereModelName,
    SphericalHarmonicTerm,
    datetime_to_julian_date,
    julian_date_to_datetime,
    gmst_angle_rad_from_jd,
    sun_position_eci_km_enhanced,
    sun_position_eci_km_simple,
    moon_position_eci_km_enhanced,
    moon_position_eci_km_simple,
    resolved_jd_utc,
    resolve_body_position_eci_km,
    resolve_sun_moon_positions,
    resolve_time_dependent_env,
    srp_shadow_factor,
    spice_sun_moon_positions_eci_km,
    spice_supported_body_names,
    EARTH_J2,
    EARTH_J3,
    EARTH_J4,
    EARTH_MU_KM3_S2,
    EARTH_RADIUS_KM,
    OrbitContext,
    OrbitPropagator,
    density_exponential,
    density_from_model,
    density_jb2008,
    density_nrlmsise00,
    density_ussa1976,
    drag_plugin,
    j2_plugin,
    j3_plugin,
    j4_plugin,
    spherical_harmonics_plugin,
    parse_spherical_harmonic_terms,
    accel_spherical_harmonics_terms,
    load_hpop_ggm03_terms,
    load_icgem_gfc_terms,
    load_real_earth_gravity_terms,
    srp_plugin,
    third_body_planets_plugin,
    third_body_moon_plugin,
    third_body_sun_plugin,
)
from sim.estimation import (
    AoITrackingEstimator,
    AttitudeEKFEstimator,
    JointStateEKFEstimator,
    JointStateEstimator,
    OrbitEKFEstimator,
    OrbitUKFEstimator,
)
from sim.metrics import EngagementMetrics, ScoreSummary, compute_engagement_metrics, compute_scores
from sim.mission import (
    AttitudeDetumbleGateMissionModule,
    BudgetedEndStateExecution,
    DesiredStateMissionStrategy,
    DefensiveMissionStrategy,
    DefensiveRICAxisBurnMissionModule,
    EndStateManeuverMissionModule,
    IntegratedCommandMissionModule,
    IntegratedCommandExecution,
    MissionExecutiveStrategy,
    PredictiveIntegratedCommandMissionModule,
    RocketGoNowExecution,
    RocketGoWhenPossibleExecution,
    RocketMissionModule,
    RocketPredefinedOrbitMissionStrategy,
    RocketPursuitMissionStrategy,
    RocketWaitOptimalExecution,
    SatelliteMissionModule,
)
from sim.optimization import (
    AttitudeTuneCase,
    ControllerAlgorithm,
    GainTuningResult,
    OptimizationResult,
    PSOConfig,
    ParameterBound,
    ParticleSwarmOptimizer,
    TuneCaseResult,
    default_case_cost,
    default_parameter_bounds,
    preset_tuning_cases,
    tune_controller_gains,
)
from sim.knowledge import (
    KnowledgeConditionConfig,
    KnowledgeEKFConfig,
    KnowledgeNoiseConfig,
    ObjectKnowledgeBase,
    TrackedObjectConfig,
)
from sim.rocket import (
    GuidanceCommand,
    HoldAttitudeGuidance,
    MaxQThrottleLimiterGuidance,
    OpenLoopPitchProgramGuidance,
    RocketAeroConfig,
    RocketAscentSimulator,
    RocketGuidanceLaw,
    RocketSimConfig,
    RocketSimResult,
    RocketState,
    RocketVehicleConfig,
)
from sim.sensors import (
    AccessConfig,
    AccessModel,
    CompositeSensorModel,
    GroundSite,
    JointStateSensor,
    NoisyOwnStateSensor,
    OwnStateSensor,
    RelativeSensor,
    SensorNoiseConfig,
)
from sim.master_simulator import run_master_simulation
from sim.utils.ground_track import ground_track_from_eci_history, split_ground_track_dateline

__all__ = [
    "ActuatorLimits",
    "SimpleActuator",
    "OrbitalActuator",
    "OrbitalActuatorLimits",
    "AttitudeActuator",
    "ReactionWheelLimits",
    "MagnetorquerLimits",
    "ThrusterPulseLimits",
    "ZeroController",
    "DeltaVManeuver",
    "ThrustLimitedDeltaVManeuver",
    "ThrustLimitedDeltaVManeuverResult",
    "ImpulsiveManeuver",
    "ImpulsiveManeuverResult",
    "AttitudeAgnosticImpulsiveManeuverer",
    "IntegratedManeuverCommand",
    "IntegratedManeuverDecision",
    "HCWLQRController",
    "HCWNoRadialLQRController",
    "HCWNoRadialManualController",
    "HCWCurvInputRectOutputController",
    "HCWInTrackCrossTrackMPCController",
    "RelativeOrbitMPCController",
    "PredictiveBurnConfig",
    "PredictiveBurnScheduler",
    "OrbitalAttitudeManeuverCoordinator",
    "StationkeepingController",
    "SafetyBarrierController",
    "RiskThresholdController",
    "RobustMPCController",
    "StochasticPolicyController",
    "ZeroTorqueController",
    "SimulationConfig",
    "SimulationSession",
    "SimulationResult",
    "SimulationSnapshot",
    "SimulationProfileName",
    "SimulationProfile",
    "PROFILE_FAST",
    "PROFILE_OPS",
    "PROFILE_HIGH_FIDELITY",
    "profile_choices",
    "get_simulation_profile",
    "resolve_dt_s",
    "resolve_steps_for_duration",
    "default_env_for_profile",
    "default_disturbance_config_for_profile",
    "build_orbit_propagator_for_profile",
    "build_default_ops_orbit_propagator",
    "AlgorithmPointer",
    "BridgePointer",
    "AgentSection",
    "SimulatorSection",
    "MonteCarloVariation",
    "MonteCarloSection",
    "OutputsSection",
    "SimulationScenarioConfig",
    "scenario_config_from_dict",
    "load_simulation_yaml",
    "validate_scenario_plugins",
    "PoseCommandGenerator",
    "DetumbleThenSlewController",
    "ECIDetumblePDController",
    "QuaternionPDController",
    "ReactionWheelPDController",
    "ReactionWheelPIDController",
    "RICDetumblePDController",
    "SmallAngleLQRController",
    "RICFrameLQRController",
    "RICFramePDController",
    "RICFramePIDController",
    "SnapAttitudeController",
    "SnapAndHoldRICAttitudeController",
    "SurrogateSnapECIController",
    "SurrogateSnapRICController",
    "SimObject",
    "Command",
    "ObjectConfig",
    "SimConfig",
    "SimLog",
    "StateBelief",
    "StateTruth",
    "DisturbanceTorqueConfig",
    "DisturbanceTorqueModel",
    "OrbitalAttitudeDynamics",
    "EARTH_MU_KM3_S2",
    "EARTH_RADIUS_KM",
    "EARTH_J2",
    "EARTH_J3",
    "EARTH_J4",
    "AtmosphereModelName",
    "SphericalHarmonicTerm",
    "datetime_to_julian_date",
    "julian_date_to_datetime",
    "gmst_angle_rad_from_jd",
    "sun_position_eci_km_enhanced",
    "sun_position_eci_km_simple",
    "moon_position_eci_km_enhanced",
    "moon_position_eci_km_simple",
    "resolved_jd_utc",
    "resolve_body_position_eci_km",
    "resolve_sun_moon_positions",
    "resolve_time_dependent_env",
    "srp_shadow_factor",
    "spice_sun_moon_positions_eci_km",
    "spice_supported_body_names",
    "OrbitContext",
    "OrbitPropagator",
    "density_exponential",
    "density_ussa1976",
    "density_nrlmsise00",
    "density_jb2008",
    "density_from_model",
    "parse_spherical_harmonic_terms",
    "accel_spherical_harmonics_terms",
    "load_hpop_ggm03_terms",
    "load_icgem_gfc_terms",
    "load_real_earth_gravity_terms",
    "j2_plugin",
    "j3_plugin",
    "j4_plugin",
    "spherical_harmonics_plugin",
    "drag_plugin",
    "srp_plugin",
    "third_body_planets_plugin",
    "third_body_moon_plugin",
    "third_body_sun_plugin",
    "OrbitEKFEstimator",
    "OrbitUKFEstimator",
    "AttitudeEKFEstimator",
    "JointStateEKFEstimator",
    "JointStateEstimator",
    "AoITrackingEstimator",
    "ScoreSummary",
    "compute_scores",
    "EngagementMetrics",
    "compute_engagement_metrics",
    "AttitudeDetumbleGateMissionModule",
    "BudgetedEndStateExecution",
    "DesiredStateMissionStrategy",
    "DefensiveMissionStrategy",
    "MissionExecutiveStrategy",
    "RocketPursuitMissionStrategy",
    "RocketPredefinedOrbitMissionStrategy",
    "RocketGoNowExecution",
    "RocketGoWhenPossibleExecution",
    "RocketWaitOptimalExecution",
    "SatelliteMissionModule",
    "DefensiveRICAxisBurnMissionModule",
    "RocketMissionModule",
    "EndStateManeuverMissionModule",
    "IntegratedCommandMissionModule",
    "IntegratedCommandExecution",
    "PredictiveIntegratedCommandMissionModule",
    "ParameterBound",
    "OptimizationResult",
    "PSOConfig",
    "ParticleSwarmOptimizer",
    "ControllerAlgorithm",
    "AttitudeTuneCase",
    "TuneCaseResult",
    "GainTuningResult",
    "default_case_cost",
    "default_parameter_bounds",
    "preset_tuning_cases",
    "tune_controller_gains",
    "KnowledgeConditionConfig",
    "KnowledgeNoiseConfig",
    "KnowledgeEKFConfig",
    "TrackedObjectConfig",
    "ObjectKnowledgeBase",
    "NoisyOwnStateSensor",
    "JointStateSensor",
    "SensorNoiseConfig",
    "OwnStateSensor",
    "RelativeSensor",
    "CompositeSensorModel",
    "AccessConfig",
    "AccessModel",
    "GroundSite",
    "ground_track_from_eci_history",
    "split_ground_track_dateline",
    "plot_ground_track",
    "plot_quaternion_components",
    "plot_body_rates",
    "plot_trajectory_frame",
    "plot_multi_trajectory_frame",
    "plot_ric_2d_projections",
    "plot_multi_ric_2d_projections",
    "plot_control_commands",
    "plot_multi_control_commands",
    "animate_rectangular_prism_attitude",
    "animate_multi_rectangular_prism_ric_curv",
    "animate_trajectory_frame",
    "animate_ground_track",
    "animate_multi_ground_track",
    "ASATPhasedScenarioConfig",
    "AgentStrategyConfig",
    "KnowledgeGateConfig",
    "run_asat_phased_engagement",
    "MonteCarloConfig",
    "run_monte_carlo",
    "run_master_simulation",
    "GuidanceCommand",
    "RocketAeroConfig",
    "RocketGuidanceLaw",
    "RocketSimConfig",
    "RocketVehicleConfig",
    "RocketState",
    "RocketSimResult",
    "RocketAscentSimulator",
    "OpenLoopPitchProgramGuidance",
    "MaxQThrottleLimiterGuidance",
    "HoldAttitudeGuidance",
]

_LAZY_IMPORTS = {
    "ASATPhasedScenarioConfig": ("sim.scenarios", "ASATPhasedScenarioConfig"),
    "AgentStrategyConfig": ("sim.scenarios", "AgentStrategyConfig"),
    "KnowledgeGateConfig": ("sim.scenarios", "KnowledgeGateConfig"),
    "MonteCarloConfig": ("sim.scenarios", "MonteCarloConfig"),
    "run_asat_phased_engagement": ("sim.scenarios", "run_asat_phased_engagement"),
    "run_monte_carlo": ("sim.scenarios", "run_monte_carlo"),
    "plot_ground_track": ("sim.utils", "plot_ground_track"),
    "plot_quaternion_components": ("sim.utils", "plot_quaternion_components"),
    "plot_body_rates": ("sim.utils", "plot_body_rates"),
    "plot_trajectory_frame": ("sim.utils", "plot_trajectory_frame"),
    "plot_multi_trajectory_frame": ("sim.utils", "plot_multi_trajectory_frame"),
    "plot_ric_2d_projections": ("sim.utils", "plot_ric_2d_projections"),
    "plot_multi_ric_2d_projections": ("sim.utils", "plot_multi_ric_2d_projections"),
    "plot_control_commands": ("sim.utils", "plot_control_commands"),
    "plot_multi_control_commands": ("sim.utils", "plot_multi_control_commands"),
    "animate_rectangular_prism_attitude": ("sim.utils", "animate_rectangular_prism_attitude"),
    "animate_multi_rectangular_prism_ric_curv": ("sim.utils", "animate_multi_rectangular_prism_ric_curv"),
    "animate_trajectory_frame": ("sim.utils", "animate_trajectory_frame"),
    "animate_ground_track": ("sim.utils", "animate_ground_track"),
    "animate_multi_ground_track": ("sim.utils", "animate_multi_ground_track"),
}


def __getattr__(name: str):
    target = _LAZY_IMPORTS.get(name)
    if target is None:
        raise AttributeError(f"module 'sim' has no attribute '{name}'")
    module_name, attr_name = target
    module = importlib.import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
