"""Public contracts for OEL v2 satellite flight-software stacks."""

from importlib import import_module

from sim.flight_software.clocks import AffineClockModel, IdealClockModel, clock_tag_elapsed_ns, compare_clock_tags
from sim.flight_software.contracts import (
    ACTUATOR_COMMAND_SCHEMA,
    CONTRACT_VERSION,
    INPUT_BATCH_SCHEMA,
    OUTPUT_SCHEMA,
    PILOT_INPUT_SCHEMA,
    SNAPSHOT_SCHEMA,
    ActuatorCommand,
    ActuatorCommandReceipt,
    ActuatorTelemetryPayload,
    AerodynamicEffectorPositionCommand,
    BootEvent,
    ClockScale,
    ClockTag,
    CmgGimbalRateCommand,
    CommandDisposition,
    ContinuousEngineCommand,
    ControlAxisSample,
    DataValidity,
    DiagnosticTelemetry,
    FlightSoftwareInputBatch,
    FlightSoftwareOutput,
    FlightSoftwareSnapshot,
    FrameId,
    GnssOwnStateMeasurement,
    GroundCommandKind,
    GroundCommandPayload,
    GyroMeasurement,
    IdealOwnStateMeasurement,
    IdealTrackedObjectStateMeasurement,
    IdealWrenchCommand,
    InputEvent,
    InputKind,
    MagnetometerMeasurement,
    MagnetorquerDipoleCommand,
    MeasurementEvent,
    ModeledFaultIndicationPayload,
    PacketId,
    PilotInputPayload,
    Quality,
    ReactionWheelTorqueCommand,
    RelativeObservationMeasurement,
    SatelliteFlightSoftware,
    ShutdownEvent,
    StackIdentity,
    StarTrackerMeasurement,
    SunVectorMeasurement,
    TaskRelease,
    TaskReleaseRequest,
    TelemetryField,
    ThrusterOnOffCommand,
    ThrusterPulseCommand,
    TimeValidity,
    ValidityInterval,
    VehicleResourceMeasurement,
)
from sim.flight_software.delivery import (
    InputDeliveryQueue,
    PacketTransport,
    TransportDisposition,
    TransportRecord,
)
from sim.flight_software.events import (
    EventTraceEntry,
    PeriodicSchedule,
    SatelliteEvent,
    SatelliteEventKernel,
    SatelliteEventPhase,
)
from sim.flight_software.frames import FrameDefinition, FrameRegistry, build_satellite_frame_registry
from sim.flight_software.loads import (
    MISSION_LOAD_SCHEMA,
    CalibrationRecord,
    ConstraintDefinition,
    ConstraintKind,
    GoalDefinition,
    GoalMode,
    MissionLoadDisposition,
    MissionLoadManager,
    MissionLoadManifest,
    MissionLoadResult,
    OnboardGeometryRecord,
    OnboardMissionConfigurationLoad,
    RequirementEvaluation,
    SafetyRequirement,
    TuningTable,
    mission_load_content_hash,
    version_satisfies,
    with_computed_content_hash,
)
from sim.flight_software.schemas import (
    assert_truth_free,
    canonical_json_bytes,
    canonical_json_text,
    canonical_loads,
    from_primitive,
    registered_schemas,
    to_primitive,
)

__all__ = [
    "ACTUATOR_COMMAND_SCHEMA",
    "BUILTIN_STACKS",
    "CONTRACT_VERSION",
    "INPUT_BATCH_SCHEMA",
    "MISSION_LOAD_SCHEMA",
    "OUTPUT_SCHEMA",
    "PILOT_INPUT_SCHEMA",
    "SNAPSHOT_SCHEMA",
    "ActuatorCommand",
    "ActuatorCommandReceipt",
    "ActuatorTelemetryPayload",
    "AerodynamicEffectorPositionCommand",
    "AffineClockModel",
    "AttitudeReferenceFlightSoftwareStack",
    "AttitudeReferenceStackConfig",
    "BootEvent",
    "BuiltinStackDescriptor",
    "CalibrationRecord",
    "ClockScale",
    "ClockTag",
    "CmgGimbalRateCommand",
    "CommandDisposition",
    "ConstraintDefinition",
    "ConstraintKind",
    "ContinuousEngineCommand",
    "ControlAxisSample",
    "DataValidity",
    "DiagnosticTelemetry",
    "FlightSoftwareInputBatch",
    "FlightSoftwareOutput",
    "FlightSoftwareSnapshot",
    "FrameDefinition",
    "FrameId",
    "FrameRegistry",
    "FlightSoftwareUseCaseProfile",
    "GameAerodynamicEffectorBinding",
    "GamePilotInputProfile",
    "GamePilotMode",
    "GamePilotReferenceFlightSoftwareStack",
    "GamePilotReferenceStackConfig",
    "GroundCommandKind",
    "GroundCommandPayload",
    "InputDeliveryQueue",
    "GnssOwnStateMeasurement",
    "GoalDefinition",
    "GoalMode",
    "GyroMeasurement",
    "IdealClockModel",
    "IdealOwnStateMeasurement",
    "IdealTrackedObjectStateMeasurement",
    "VehicleResourceMeasurement",
    "IdealWrenchCommand",
    "InputEvent",
    "InputKind",
    "MagnetometerMeasurement",
    "MagnetorquerDipoleCommand",
    "MeasurementEvent",
    "ModeledFaultIndicationPayload",
    "MissionLoadDisposition",
    "MissionLoadManager",
    "MissionLoadManifest",
    "MissionLoadResult",
    "MaterializedFlightSoftwareProfile",
    "LowThrustReferenceFlightSoftwareStack",
    "LowThrustReferenceStackConfig",
    "OnboardGeometryRecord",
    "OnboardMissionConfigurationLoad",
    "OrbitReferenceFlightSoftwareStack",
    "OrbitReferenceStackConfig",
    "PacketId",
    "PacketTransport",
    "PassiveFlightSoftwareStack",
    "PassiveStackConfig",
    "PeriodicSchedule",
    "PilotInputPayload",
    "Quality",
    "PROFILE_CATALOG_VERSION",
    "PROFILE_QUALIFICATION_GATES",
    "ProfileParameterRequirement",
    "ReactionWheelTorqueCommand",
    "RelativeObservationMeasurement",
    "RpoReferenceFlightSoftwareStack",
    "RpoReferenceStackConfig",
    "RequirementEvaluation",
    "SafetyRequirement",
    "SatelliteFlightSoftware",
    "SatelliteEvent",
    "SatelliteEventKernel",
    "SatelliteEventPhase",
    "ShutdownEvent",
    "StackIdentity",
    "StackMaturity",
    "STACK_VERSION",
    "TranslationReferenceStackConfig",
    "StarTrackerMeasurement",
    "SunVectorMeasurement",
    "TaskReleaseRequest",
    "TaskRelease",
    "TelemetryField",
    "ThrusterOnOffCommand",
    "ThrusterPulseCommand",
    "TimeValidity",
    "TransportDisposition",
    "TransportRecord",
    "EventTraceEntry",
    "TuningTable",
    "ValidityInterval",
    "assert_truth_free",
    "build_satellite_frame_registry",
    "build_builtin_stack",
    "canonical_json_bytes",
    "canonical_json_text",
    "canonical_loads",
    "clock_tag_elapsed_ns",
    "compare_clock_tags",
    "from_primitive",
    "mission_load_content_hash",
    "registered_schemas",
    "to_primitive",
    "version_satisfies",
    "with_computed_content_hash",
    "STACK_CATALOG",
    "StackCatalogEntry",
    "resolve_stack",
    "stack_catalog",
    "validate_stack_hardware",
    "USE_CASE_PROFILES",
    "materialize_use_case_profile",
    "resolve_use_case_profile",
    "use_case_profiles",
    "validate_use_case_profile_catalog",
]

_REFERENCE_STACK_EXPORTS = frozenset(
    {
        "BUILTIN_STACKS",
        "STACK_VERSION",
        "AttitudeReferenceFlightSoftwareStack",
        "AttitudeReferenceStackConfig",
        "BuiltinStackDescriptor",
        "LowThrustReferenceFlightSoftwareStack",
        "LowThrustReferenceStackConfig",
        "OrbitReferenceFlightSoftwareStack",
        "OrbitReferenceStackConfig",
        "PassiveFlightSoftwareStack",
        "PassiveStackConfig",
        "RpoReferenceFlightSoftwareStack",
        "RpoReferenceStackConfig",
        "StackMaturity",
        "build_builtin_stack",
        "TranslationReferenceStackConfig",
    }
)

_GAME_STACK_EXPORTS = frozenset(
    {
        "GameAerodynamicEffectorBinding",
        "GamePilotInputProfile",
        "GamePilotMode",
        "GamePilotReferenceFlightSoftwareStack",
        "GamePilotReferenceStackConfig",
    }
)

_CATALOG_EXPORTS = frozenset(
    {
        "STACK_CATALOG",
        "StackCatalogEntry",
        "resolve_stack",
        "stack_catalog",
        "validate_stack_hardware",
    }
)

_PROFILE_EXPORTS = frozenset(
    {
        "FlightSoftwareUseCaseProfile",
        "MaterializedFlightSoftwareProfile",
        "PROFILE_CATALOG_VERSION",
        "PROFILE_QUALIFICATION_GATES",
        "ProfileParameterRequirement",
        "USE_CASE_PROFILES",
        "materialize_use_case_profile",
        "resolve_use_case_profile",
        "use_case_profiles",
        "validate_use_case_profile_catalog",
    }
)


def __getattr__(name: str) -> object:
    if name in _GAME_STACK_EXPORTS:
        module = import_module("sim.flight_software.game_stacks")
    elif name in _PROFILE_EXPORTS:
        module = import_module("sim.flight_software.profiles")
    elif name in _CATALOG_EXPORTS:
        module = import_module("sim.flight_software.catalog")
    elif name in _REFERENCE_STACK_EXPORTS:
        module = import_module("sim.flight_software.reference_stacks")
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(module, name)
    globals()[name] = value
    return value
