"""Post-run domain analysis services built on deterministic OEL evidence."""

from sim.analysis.communications_coverage import (
    COMMUNICATIONS_COVERAGE_CONTRACT_VERSION,
    CommunicationsCoverageConfig,
    CommunicationsCoverageResult,
    EarthTerminalProfile,
    evaluate_communications_coverage,
    write_communications_coverage_artifacts,
)
from sim.analysis.coverage_aggregation import (
    CONSTELLATION_COVERAGE_CONTRACT_VERSION,
    ConstellationCoverageConfig,
    ConstellationCoverageResult,
    evaluate_constellation_coverage,
    write_constellation_coverage_artifacts,
)
from sim.analysis.coverage_queries import (
    COVERAGE_QUERY_SCHEMA_VERSION,
    CoveragePointQuery,
    CoverageQueryResult,
    CoverageRegionMask,
    evaluate_coverage_queries,
    validate_global_coverage_product,
    write_coverage_query_artifacts,
)
from sim.analysis.coverage_sensitivity import (
    COVERAGE_SENSITIVITY_CONTRACT_VERSION,
    CoverageSensitivityCriteria,
    CoverageSensitivityResult,
    evaluate_coverage_sensitivity,
    write_coverage_sensitivity_evidence,
)
from sim.analysis.coverage_tasking import (
    COVERAGE_TASKING_CONTRACT_VERSION,
    CoverageTaskingConfig,
    CoverageTaskingResult,
    TaskingConstraints,
    TaskOpportunity,
    optimize_coverage_tasking,
    write_coverage_tasking_artifacts,
)
from sim.analysis.directed_link import (
    DIRECTED_LINK_CONTRACT_VERSION,
    DirectedLinkConfig,
    DirectedLinkResult,
    LinkTerminal,
    LinkWindowEvidence,
    TerminalPattern,
    evaluate_directed_link,
    evaluate_directed_link_sample,
    fixed_wgs84_site_history,
    free_space_link_ledger,
    spacecraft_endpoint_history,
    write_directed_link_artifacts,
)
from sim.analysis.directed_link_runtime import (
    RUNTIME_LINK_MONITOR_CONTRACT_VERSION,
    AuthorizedLinkRuntimeMonitor,
    RuntimeLinkEvaluation,
    RuntimeLinkEvent,
    RuntimeLinkMonitorConfig,
)
from sim.analysis.global_coverage import (
    GLOBAL_COVERAGE_CONTRACT_VERSION,
    GlobalCoverageConfig,
    GlobalCoverageResult,
    evaluate_global_coverage,
    write_global_coverage_artifacts,
)
from sim.analysis.history_adapters import (
    AnalysisHistory,
    AnalysisState,
    directed_link_refinement_evaluator,
    evaluate_history_directed_link,
    evaluate_history_global_coverage,
    global_coverage_refinement_evaluator,
    history_from_ogp_product,
    history_from_ogp_store,
    history_from_review_store,
    history_from_single_run,
)
from sim.analysis.mission_recovery import build_mission_recovery_summary
from sim.analysis.rich_coverage import (
    RICH_COVERAGE_CONTRACT_VERSION,
    RichCoverageConfig,
    RichCoverageResult,
    evaluate_rich_coverage,
    write_rich_coverage_artifacts,
)
from sim.analysis.sensor_footprint_geometry import (
    HardFOVPattern,
    SurfaceServiceConstraints,
)

__all__ = [
    "COMMUNICATIONS_COVERAGE_CONTRACT_VERSION",
    "CONSTELLATION_COVERAGE_CONTRACT_VERSION",
    "COVERAGE_TASKING_CONTRACT_VERSION",
    "COVERAGE_QUERY_SCHEMA_VERSION",
    "COVERAGE_SENSITIVITY_CONTRACT_VERSION",
    "DIRECTED_LINK_CONTRACT_VERSION",
    "GLOBAL_COVERAGE_CONTRACT_VERSION",
    "RICH_COVERAGE_CONTRACT_VERSION",
    "RUNTIME_LINK_MONITOR_CONTRACT_VERSION",
    "AuthorizedLinkRuntimeMonitor",
    "AnalysisHistory",
    "AnalysisState",
    "CommunicationsCoverageConfig",
    "CommunicationsCoverageResult",
    "ConstellationCoverageConfig",
    "ConstellationCoverageResult",
    "CoveragePointQuery",
    "CoverageQueryResult",
    "CoverageRegionMask",
    "CoverageSensitivityCriteria",
    "CoverageSensitivityResult",
    "CoverageTaskingConfig",
    "CoverageTaskingResult",
    "DirectedLinkConfig",
    "DirectedLinkResult",
    "EarthTerminalProfile",
    "GlobalCoverageConfig",
    "GlobalCoverageResult",
    "HardFOVPattern",
    "LinkTerminal",
    "LinkWindowEvidence",
    "RichCoverageConfig",
    "RichCoverageResult",
    "RuntimeLinkEvaluation",
    "RuntimeLinkEvent",
    "RuntimeLinkMonitorConfig",
    "SurfaceServiceConstraints",
    "TaskOpportunity",
    "TaskingConstraints",
    "TerminalPattern",
    "build_mission_recovery_summary",
    "evaluate_communications_coverage",
    "evaluate_constellation_coverage",
    "evaluate_coverage_queries",
    "evaluate_coverage_sensitivity",
    "evaluate_directed_link",
    "evaluate_directed_link_sample",
    "evaluate_global_coverage",
    "evaluate_rich_coverage",
    "fixed_wgs84_site_history",
    "free_space_link_ledger",
    "directed_link_refinement_evaluator",
    "evaluate_history_directed_link",
    "evaluate_history_global_coverage",
    "global_coverage_refinement_evaluator",
    "history_from_ogp_product",
    "history_from_ogp_store",
    "history_from_review_store",
    "history_from_single_run",
    "optimize_coverage_tasking",
    "spacecraft_endpoint_history",
    "validate_global_coverage_product",
    "write_communications_coverage_artifacts",
    "write_constellation_coverage_artifacts",
    "write_coverage_query_artifacts",
    "write_coverage_sensitivity_evidence",
    "write_coverage_tasking_artifacts",
    "write_directed_link_artifacts",
    "write_global_coverage_artifacts",
    "write_rich_coverage_artifacts",
]
