from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QDoubleSpinBox,
    QFormLayout,
    QFrame,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QPlainTextEdit,
    QPushButton,
    QScrollArea,
    QSpinBox,
    QStackedWidget,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)


def build_scenario_tab(owner) -> QWidget:
    tab = QWidget()
    layout = QFormLayout(tab)
    owner.scenario_form_layout = layout
    owner.scenario_name_edit = QLineEdit()
    owner.scenario_name_edit.setMinimumWidth(320)
    owner.scenario_description_edit = QLineEdit()
    owner.scenario_description_edit.setMinimumWidth(320)
    owner.duration_spin = QDoubleSpinBox()
    owner.duration_spin.setRange(0.001, 1.0e9)
    owner.duration_spin.setDecimals(3)
    owner.duration_spin.setValue(3600.0)
    owner.dt_spin = QDoubleSpinBox()
    owner.dt_spin.setRange(0.000001, 1.0e6)
    owner.dt_spin.setDecimals(6)
    owner.dt_spin.setValue(1.0)
    owner.orbit_integrator_combo = QComboBox()
    owner.orbit_integrator_combo.addItems(owner.orbit_integrator_options)
    owner.orbit_adaptive_atol_spin = owner._make_free_spinbox(decimals=12)
    owner.orbit_adaptive_atol_spin.setRange(0.0, 1.0)
    owner.orbit_adaptive_atol_spin.setValue(1.0e-9)
    owner.orbit_adaptive_rtol_spin = owner._make_free_spinbox(decimals=12)
    owner.orbit_adaptive_rtol_spin.setRange(0.0, 1.0)
    owner.orbit_adaptive_rtol_spin.setValue(1.0e-7)
    owner.output_mode_combo = QComboBox()
    owner.output_mode_combo.addItems(owner.output_modes)
    owner.output_dir_edit = QLineEdit()
    owner.output_dir_edit.setMinimumWidth(320)
    owner.output_dir_browse_button = QPushButton("Browse...")
    owner.output_dir_browse_button.clicked.connect(owner._browse_output_directory)
    owner.orbit_substep_enabled_check = QCheckBox("Orbit Substep")
    owner.orbit_substep_spin = owner._make_free_spinbox()
    owner.attitude_substep_enabled_check = QCheckBox("Attitude Substep")
    owner.attitude_substep_spin = owner._make_free_spinbox()
    owner.attitude_enabled_check = QCheckBox("Enable Attitude Dynamics")
    owner.orbit_j2_check = QCheckBox("J2")
    owner.orbit_j3_check = QCheckBox("J3")
    owner.orbit_j4_check = QCheckBox("J4")
    owner.orbit_drag_check = QCheckBox("Drag")
    owner.orbit_srp_check = QCheckBox("SRP")
    owner.orbit_moon_check = QCheckBox("Third-Body Moon")
    owner.orbit_sun_check = QCheckBox("Third-Body Sun")
    owner.att_gg_check = QCheckBox("Gravity Gradient")
    owner.att_magnetic_check = QCheckBox("Magnetic")
    owner.att_drag_check = QCheckBox("Drag Torque")
    owner.att_srp_check = QCheckBox("SRP Torque")

    layout.addRow("Scenario Name", owner.scenario_name_edit)
    layout.addRow("Scenario Description", owner.scenario_description_edit)
    layout.addRow("Duration (s)", owner.duration_spin)
    layout.addRow("dt (s)", owner.dt_spin)
    layout.addRow("Orbit Integrator", owner.orbit_integrator_combo)
    layout.addRow("Output Mode", owner.output_mode_combo)
    output_dir_row = QWidget()
    output_dir_layout = QHBoxLayout(output_dir_row)
    output_dir_layout.setContentsMargins(0, 0, 0, 0)
    output_dir_layout.setSpacing(6)
    output_dir_layout.addWidget(owner.output_dir_edit, 1)
    output_dir_layout.addWidget(owner.output_dir_browse_button)
    layout.addRow("Output Directory", output_dir_row)
    layout.addRow("Adaptive Abs Tol", owner.orbit_adaptive_atol_spin)
    layout.addRow("Adaptive Rel Tol", owner.orbit_adaptive_rtol_spin)
    orbit_substep_row = QWidget()
    orbit_substep_layout = QHBoxLayout(orbit_substep_row)
    orbit_substep_layout.setContentsMargins(0, 0, 0, 0)
    orbit_substep_layout.setSpacing(4)
    orbit_substep_layout.addWidget(owner.orbit_substep_enabled_check)
    orbit_substep_layout.addWidget(owner.orbit_substep_spin)
    orbit_substep_layout.addStretch(1)
    layout.addRow(orbit_substep_row)
    attitude_substep_row = QWidget()
    attitude_substep_layout = QHBoxLayout(attitude_substep_row)
    attitude_substep_layout.setContentsMargins(0, 0, 0, 0)
    attitude_substep_layout.setSpacing(4)
    attitude_substep_layout.addWidget(owner.attitude_substep_enabled_check)
    attitude_substep_layout.addWidget(owner.attitude_substep_spin)
    attitude_substep_layout.addStretch(1)
    layout.addRow(attitude_substep_row)
    layout.addRow(owner.attitude_enabled_check)
    orbit_perturbations = QWidget()
    orbit_perturbations_layout = QGridLayout(orbit_perturbations)
    orbit_perturbations_layout.setContentsMargins(0, 0, 0, 0)
    orbit_perturbations_layout.addWidget(owner.orbit_j2_check, 0, 0)
    orbit_perturbations_layout.addWidget(owner.orbit_j3_check, 0, 1)
    orbit_perturbations_layout.addWidget(owner.orbit_j4_check, 0, 2)
    orbit_perturbations_layout.addWidget(owner.orbit_drag_check, 1, 0)
    orbit_perturbations_layout.addWidget(owner.orbit_srp_check, 1, 1)
    orbit_perturbations_layout.addWidget(owner.orbit_moon_check, 2, 0)
    orbit_perturbations_layout.addWidget(owner.orbit_sun_check, 2, 1)
    layout.addRow("Orbital Perturbations", orbit_perturbations)
    attitude_disturbances = QWidget()
    attitude_disturbances_layout = QGridLayout(attitude_disturbances)
    attitude_disturbances_layout.setContentsMargins(0, 0, 0, 0)
    attitude_disturbances_layout.addWidget(owner.att_gg_check, 0, 0)
    attitude_disturbances_layout.addWidget(owner.att_magnetic_check, 0, 1)
    attitude_disturbances_layout.addWidget(owner.att_drag_check, 1, 0)
    attitude_disturbances_layout.addWidget(owner.att_srp_check, 1, 1)
    layout.addRow("Attitude Disturbances", attitude_disturbances)
    return tab


def build_monte_carlo_tab(owner) -> QWidget:
    tab = QWidget()
    layout = QVBoxLayout(tab)
    owner.mc_enabled_check = QCheckBox("Enable Analysis")
    owner.analysis_study_type_combo = QComboBox()
    owner._populate_value_combo(owner.analysis_study_type_combo, owner.analysis_study_types)
    owner.analysis_count_label = QLabel("Iterations")
    owner.mc_iterations_spin = QSpinBox()
    owner.mc_iterations_spin.setRange(1, 1000000)
    owner.mc_parallel_check = QCheckBox("Parallel")
    owner.mc_workers_spin = QSpinBox()
    owner.mc_workers_spin.setRange(0, 1024)
    owner.analysis_seed_label = QLabel("Base Seed")
    owner.mc_base_seed_spin = QSpinBox()
    owner.mc_base_seed_spin.setRange(0, 2**31 - 1)
    execution_row = QHBoxLayout()
    execution_row.addWidget(owner.mc_enabled_check)
    execution_row.addSpacing(12)
    execution_row.addWidget(QLabel("Study"))
    execution_row.addWidget(owner.analysis_study_type_combo)
    execution_row.addSpacing(12)
    execution_row.addWidget(owner.analysis_count_label)
    execution_row.addWidget(owner.mc_iterations_spin)
    execution_row.addSpacing(12)
    execution_row.addWidget(owner.mc_parallel_check)
    execution_row.addWidget(QLabel("Workers (0=auto)"))
    execution_row.addWidget(owner.mc_workers_spin)
    execution_row.addSpacing(12)
    execution_row.addWidget(owner.analysis_seed_label)
    execution_row.addWidget(owner.mc_base_seed_spin)
    execution_row.addStretch(1)
    layout.addLayout(execution_row)

    owner.analysis_settings_box = QGroupBox("Study Settings")
    analysis_settings_layout = QFormLayout(owner.analysis_settings_box)
    owner.sensitivity_method_combo = QComboBox()
    owner._populate_value_combo(owner.sensitivity_method_combo, owner.sensitivity_methods)
    owner.analysis_lhs_samples_spin = QSpinBox()
    owner.analysis_lhs_samples_spin.setRange(1, 1000000)
    owner.analysis_metrics_edit = QPlainTextEdit()
    owner.analysis_metrics_edit.setPlaceholderText(
        "summary.duration_s\n"
        "derived.closest_approach_km\n"
        "summary.thrust_stats.chaser.total_dv_m_s"
    )
    owner.analysis_metrics_edit.setMaximumHeight(78)
    owner.analysis_baseline_enable_check = QCheckBox("Enable Baseline Comparison")
    owner.analysis_baseline_path_edit = QLineEdit()
    owner.analysis_baseline_path_edit.setPlaceholderText("Optional baseline summary JSON")
    owner.analysis_baseline_browse_button = QPushButton("Browse...")
    owner.analysis_baseline_browse_button.clicked.connect(owner._browse_analysis_baseline_summary)
    baseline_row = QWidget()
    baseline_row_layout = QHBoxLayout(baseline_row)
    baseline_row_layout.setContentsMargins(0, 0, 0, 0)
    baseline_row_layout.setSpacing(6)
    baseline_row_layout.addWidget(owner.analysis_baseline_path_edit, 1)
    baseline_row_layout.addWidget(owner.analysis_baseline_browse_button)
    owner.analysis_help_label = QLabel("")
    owner.analysis_help_label.setWordWrap(True)
    analysis_settings_layout.addRow("Sensitivity Method", owner.sensitivity_method_combo)
    analysis_settings_layout.addRow("LHS Samples", owner.analysis_lhs_samples_spin)
    analysis_settings_layout.addRow("Tracked Metrics", owner.analysis_metrics_edit)
    analysis_settings_layout.addRow(owner.analysis_baseline_enable_check)
    analysis_settings_layout.addRow("Baseline Summary", baseline_row)
    analysis_settings_layout.addRow("Notes", owner.analysis_help_label)
    layout.addWidget(owner.analysis_settings_box)

    variations_split = QHBoxLayout()
    group_box_style = (
        "QGroupBox {"
        " font-weight: normal;"
        " margin-top: 18px;"
        "}"
        "QGroupBox::title {"
        " subcontrol-origin: margin;"
        " subcontrol-position: top left;"
        " padding: 0 4px;"
        " top: -3px;"
        "}"
    )
    owner.analysis_inputs_box = QGroupBox("Study Inputs")
    variations_box = owner.analysis_inputs_box
    variations_box.setStyleSheet(group_box_style)
    variations_box_layout = QVBoxLayout(variations_box)
    owner.mc_variations_list = QListWidget()
    owner.mc_variations_list.currentRowChanged.connect(owner._on_mc_variation_selected)
    variations_box_layout.addWidget(owner.mc_variations_list)
    variations_split.addWidget(variations_box, 2)

    owner.analysis_editor_box = QGroupBox("Input Editor")
    editor_box = owner.analysis_editor_box
    editor_box.setStyleSheet(group_box_style)
    editor_box_layout = QHBoxLayout(editor_box)
    editor_box_layout.setContentsMargins(8, 16, 8, 8)
    editor_box_layout.setSpacing(4)
    editor_form = QFormLayout()
    editor_form.setFieldGrowthPolicy(QFormLayout.FieldsStayAtSizeHint)
    editor_box_layout.addLayout(editor_form, 0)
    button_column = QVBoxLayout()
    button_column.setContentsMargins(0, 0, 0, 0)
    button_column.setSpacing(4)
    owner.mc_new_variation_button = QPushButton("New")
    owner.mc_new_variation_button.clicked.connect(owner._clear_mc_variation_editor)
    button_column.addWidget(owner.mc_new_variation_button)
    owner.mc_add_update_variation_button = QPushButton("Add / Update")
    owner.mc_add_update_variation_button.clicked.connect(owner._on_add_or_update_mc_variation)
    button_column.addWidget(owner.mc_add_update_variation_button)
    owner.mc_remove_variation_button = QPushButton("Remove")
    owner.mc_remove_variation_button.clicked.connect(owner._on_remove_mc_variation)
    button_column.addWidget(owner.mc_remove_variation_button)
    button_column.addStretch(1)
    editor_box_layout.addLayout(button_column)
    editor_box_layout.addStretch(1)
    owner.mc_variation_form = editor_form
    owner.mc_category_combo = QComboBox()
    owner.mc_category_combo.currentIndexChanged.connect(owner._refresh_mc_parameter_options)
    editor_form.addRow("Category", owner.mc_category_combo)

    owner.mc_parameter_combo = QComboBox()
    editor_form.addRow("Parameter", owner.mc_parameter_combo)

    owner.mc_custom_path_edit = QLineEdit()
    owner.mc_custom_path_edit.setPlaceholderText("simulator.environment.atmosphere_env.solar_flux_f107")
    editor_form.addRow("Custom Path", owner.mc_custom_path_edit)

    owner.mc_mode_combo = QComboBox()
    owner._populate_value_combo(owner.mc_mode_combo, [(mode, mode) for mode in owner.mc_mode_options])
    owner.mc_mode_combo.currentTextChanged.connect(owner._refresh_mc_mode_ui)
    editor_form.addRow("Mode", owner.mc_mode_combo)

    owner.mc_mode_stack = QStackedWidget()
    choice_page = QWidget()
    choice_form = QFormLayout(choice_page)
    owner.mc_choice_options_edit = QLineEdit()
    owner.mc_choice_options_edit.setPlaceholderText("0.5, 1.0, 1.5")
    choice_form.addRow("Options", owner.mc_choice_options_edit)
    owner.mc_mode_stack.addWidget(choice_page)

    uniform_page = QWidget()
    uniform_form = QFormLayout(uniform_page)
    owner.mc_uniform_low_spin = owner._make_free_spinbox()
    owner.mc_uniform_high_spin = owner._make_free_spinbox()
    uniform_form.addRow("Low", owner.mc_uniform_low_spin)
    uniform_form.addRow("High", owner.mc_uniform_high_spin)
    owner.mc_mode_stack.addWidget(uniform_page)

    normal_page = QWidget()
    normal_form = QFormLayout(normal_page)
    owner.mc_normal_mean_spin = owner._make_free_spinbox()
    owner.mc_normal_std_spin = owner._make_free_spinbox()
    normal_form.addRow("Mean", owner.mc_normal_mean_spin)
    normal_form.addRow("Std", owner.mc_normal_std_spin)
    owner.mc_mode_stack.addWidget(normal_page)
    editor_form.addRow("Settings", owner.mc_mode_stack)

    variations_split.addWidget(editor_box, 3)
    layout.addLayout(variations_split, 1)
    owner._rebuild_mc_category_combo()
    owner._refresh_mc_parameter_options()
    owner._refresh_mc_mode_ui()
    owner._refresh_analysis_editor_ui()
    return tab


def build_objects_tab(owner) -> QWidget:
    tab = QWidget()
    layout = QGridLayout(tab)

    target_box = QFrame()
    target_box.setFrameShape(QFrame.StyledPanel)
    target_box.setFrameShadow(QFrame.Plain)
    target_form = QFormLayout(target_box)
    owner.target_enabled = QCheckBox("Enabled")
    owner.target_preset = QComboBox()
    owner._configure_compact_combo(owner.target_preset)
    owner.target_preset.addItems(owner.satellite_preset_options)
    owner.target_dry_mass = QDoubleSpinBox()
    owner.target_dry_mass.setRange(0.0, 1.0e9)
    owner.target_dry_mass.setDecimals(3)
    owner.target_fuel_mass = QDoubleSpinBox()
    owner.target_fuel_mass.setRange(0.0, 1.0e9)
    owner.target_fuel_mass.setDecimals(3)
    owner.target_a = QDoubleSpinBox()
    owner.target_a.setRange(1.0, 1.0e9)
    owner.target_a.setDecimals(3)
    owner.target_ecc = QDoubleSpinBox()
    owner.target_ecc.setRange(0.0, 100.0)
    owner.target_ecc.setDecimals(6)
    owner.target_inc = QDoubleSpinBox()
    owner.target_inc.setRange(-360.0, 360.0)
    owner.target_inc.setDecimals(3)
    owner.target_raan = QDoubleSpinBox()
    owner.target_raan.setRange(-360.0, 360.0)
    owner.target_raan.setDecimals(3)
    owner.target_argp = QDoubleSpinBox()
    owner.target_argp.setRange(-360.0, 360.0)
    owner.target_argp.setDecimals(3)
    owner.target_ta = QDoubleSpinBox()
    owner.target_ta.setRange(-360.0, 360.0)
    owner.target_ta.setDecimals(3)
    target_form.addRow(owner.target_enabled)
    target_form.addRow("Preset", owner.target_preset)
    target_form.addRow("Dry Mass (kg)", owner.target_dry_mass)
    target_form.addRow("Fuel Mass (kg)", owner.target_fuel_mass)
    owner.target_initial_state_button = owner._make_section_toggle_button("target")
    target_form.addRow("Initial State", owner.target_initial_state_button)
    owner.target_initial_state_container = QWidget()
    target_initial_state_form = QFormLayout(owner.target_initial_state_container)
    target_initial_state_form.setContentsMargins(0, 0, 0, 0)
    target_initial_state_form.addRow("a_km", owner.target_a)
    target_initial_state_form.addRow("ecc", owner.target_ecc)
    target_initial_state_form.addRow("inc_deg", owner.target_inc)
    target_initial_state_form.addRow("raan_deg", owner.target_raan)
    target_initial_state_form.addRow("argp_deg", owner.target_argp)
    target_initial_state_form.addRow("true_anomaly_deg", owner.target_ta)
    target_form.addRow(owner.target_initial_state_container)
    owner.target_strategy_combo = owner._make_pointer_combo(owner.mission_strategy_options["target"])
    owner.target_execution_combo = owner._make_pointer_combo(owner.mission_execution_options["target"])
    owner.target_orbit_control_combo = owner._make_pointer_combo(owner.orbit_control_options["target"])
    owner.target_attitude_control_combo = owner._make_pointer_combo(owner.attitude_control_options["target"])
    owner.target_gnc_button = owner._make_section_toggle_button("target", "gnc")
    target_form.addRow("GNC", owner.target_gnc_button)
    owner.target_gnc_container = QWidget()
    target_gnc_form = QFormLayout(owner.target_gnc_container)
    target_gnc_form.setContentsMargins(0, 0, 0, 0)
    target_gnc_form.addRow("Mission Strategy", owner._make_pointer_editor_row(owner.target_strategy_combo, "target", "mission_strategy"))
    target_gnc_form.addRow("Mission Execution", owner._make_pointer_editor_row(owner.target_execution_combo, "target", "mission_execution"))
    target_gnc_form.addRow("Orbit Control", owner._make_pointer_editor_row(owner.target_orbit_control_combo, "target", "orbit_control"))
    target_gnc_form.addRow("Attitude Control", owner._make_pointer_editor_row(owner.target_attitude_control_combo, "target", "attitude_control"))
    target_form.addRow(owner.target_gnc_container)
    owner.target_knowledge_button = owner._make_section_toggle_button("target", "knowledge")
    target_form.addRow("Knowledge / Sensor", owner.target_knowledge_button)
    owner.target_knowledge_container = owner._build_knowledge_editor("target")
    target_form.addRow(owner.target_knowledge_container)
    layout.addWidget(owner._wrap_object_panel(target_box, "Target"), 0, 0)

    chaser_box = QFrame()
    chaser_box.setFrameShape(QFrame.StyledPanel)
    chaser_box.setFrameShadow(QFrame.Plain)
    chaser_form = QFormLayout(chaser_box)
    owner.chaser_enabled = QCheckBox("Enabled")
    owner.chaser_preset = QComboBox()
    owner._configure_compact_combo(owner.chaser_preset)
    owner.chaser_preset.addItems(owner.satellite_preset_options)
    owner.chaser_dry_mass = QDoubleSpinBox()
    owner.chaser_dry_mass.setRange(0.0, 1.0e9)
    owner.chaser_dry_mass.setDecimals(3)
    owner.chaser_fuel_mass = QDoubleSpinBox()
    owner.chaser_fuel_mass.setRange(0.0, 1.0e9)
    owner.chaser_fuel_mass.setDecimals(3)
    owner.chaser_init_mode = QComboBox()
    owner._populate_value_combo(owner.chaser_init_mode, [(mode, mode) for mode in owner.chaser_init_mode_options])
    owner.chaser_init_values = [owner._make_free_spinbox() for _ in range(6)]
    owner.chaser_deploy_time = owner._make_free_spinbox()
    chaser_form.addRow(owner.chaser_enabled)
    chaser_form.addRow("Preset", owner.chaser_preset)
    chaser_form.addRow("Dry Mass (kg)", owner.chaser_dry_mass)
    chaser_form.addRow("Fuel Mass (kg)", owner.chaser_fuel_mass)
    owner.chaser_initial_state_button = owner._make_section_toggle_button("chaser")
    chaser_form.addRow("Initial State", owner.chaser_initial_state_button)
    owner.chaser_initial_state_container = QWidget()
    chaser_initial_state_form = QFormLayout(owner.chaser_initial_state_container)
    chaser_initial_state_form.setContentsMargins(0, 0, 0, 0)
    chaser_initial_state_form.addRow("Init Mode", owner.chaser_init_mode)
    chaser_initial_state_form.addRow("Deploy Time (s)", owner.chaser_deploy_time)
    for i, widget in enumerate(owner.chaser_init_values):
        chaser_initial_state_form.addRow(f"Init[{i}]", widget)
    chaser_form.addRow(owner.chaser_initial_state_container)
    owner.chaser_strategy_combo = owner._make_pointer_combo(owner.mission_strategy_options["chaser"])
    owner.chaser_execution_combo = owner._make_pointer_combo(owner.mission_execution_options["chaser"])
    owner.chaser_orbit_control_combo = owner._make_pointer_combo(owner.orbit_control_options["chaser"])
    owner.chaser_attitude_control_combo = owner._make_pointer_combo(owner.attitude_control_options["chaser"])
    owner.chaser_gnc_button = owner._make_section_toggle_button("chaser", "gnc")
    chaser_form.addRow("GNC", owner.chaser_gnc_button)
    owner.chaser_gnc_container = QWidget()
    chaser_gnc_form = QFormLayout(owner.chaser_gnc_container)
    chaser_gnc_form.setContentsMargins(0, 0, 0, 0)
    chaser_gnc_form.addRow("Mission Strategy", owner._make_pointer_editor_row(owner.chaser_strategy_combo, "chaser", "mission_strategy"))
    chaser_gnc_form.addRow("Mission Execution", owner._make_pointer_editor_row(owner.chaser_execution_combo, "chaser", "mission_execution"))
    chaser_gnc_form.addRow("Orbit Control", owner._make_pointer_editor_row(owner.chaser_orbit_control_combo, "chaser", "orbit_control"))
    chaser_gnc_form.addRow("Attitude Control", owner._make_pointer_editor_row(owner.chaser_attitude_control_combo, "chaser", "attitude_control"))
    chaser_form.addRow(owner.chaser_gnc_container)
    owner.chaser_knowledge_button = owner._make_section_toggle_button("chaser", "knowledge")
    chaser_form.addRow("Knowledge / Sensor", owner.chaser_knowledge_button)
    owner.chaser_knowledge_container = owner._build_knowledge_editor("chaser")
    chaser_form.addRow(owner.chaser_knowledge_container)
    layout.addWidget(owner._wrap_object_panel(chaser_box, "Chaser"), 0, 1)

    rocket_box = QFrame()
    rocket_box.setFrameShape(QFrame.StyledPanel)
    rocket_box.setFrameShadow(QFrame.Plain)
    rocket_form = QFormLayout(rocket_box)
    owner.rocket_enabled = QCheckBox("Enabled")
    owner.rocket_preset = QComboBox()
    owner._configure_compact_combo(owner.rocket_preset)
    owner.rocket_preset.addItems(owner.rocket_preset_options)
    owner.rocket_payload = QDoubleSpinBox()
    owner.rocket_payload.setRange(0.0, 1.0e9)
    owner.rocket_payload.setDecimals(3)
    owner.rocket_launch_lat = owner._make_free_spinbox()
    owner.rocket_launch_lon = owner._make_free_spinbox()
    owner.rocket_launch_alt = owner._make_free_spinbox()
    owner.rocket_launch_az = owner._make_free_spinbox()
    owner.rocket_launch_lat.setMaximumWidth(owner.rocket_payload.maximumWidth())
    owner.rocket_launch_lon.setMaximumWidth(owner.rocket_payload.maximumWidth())
    owner.rocket_launch_alt.setMaximumWidth(owner.rocket_payload.maximumWidth())
    owner.rocket_launch_az.setMaximumWidth(owner.rocket_payload.maximumWidth())
    rocket_form.addRow(owner.rocket_enabled)
    rocket_form.addRow("Stack Preset", owner.rocket_preset)
    rocket_form.addRow("Payload Mass (kg)", owner.rocket_payload)
    owner.rocket_initial_state_button = owner._make_section_toggle_button("rocket")
    rocket_form.addRow("Initial State", owner.rocket_initial_state_button)
    owner.rocket_initial_state_container = QWidget()
    rocket_initial_state_form = QFormLayout(owner.rocket_initial_state_container)
    rocket_initial_state_form.setContentsMargins(0, 0, 0, 0)
    rocket_initial_state_form.addRow("Launch Lat (deg)", owner.rocket_launch_lat)
    rocket_initial_state_form.addRow("Launch Lon (deg)", owner.rocket_launch_lon)
    rocket_initial_state_form.addRow("Launch Alt (km)", owner.rocket_launch_alt)
    rocket_initial_state_form.addRow("Launch Azimuth (deg)", owner.rocket_launch_az)
    rocket_form.addRow(owner.rocket_initial_state_container)
    owner.rocket_strategy_combo = owner._make_pointer_combo(owner.mission_strategy_options["rocket"])
    owner.rocket_execution_combo = owner._make_pointer_combo(owner.mission_execution_options["rocket"])
    owner.rocket_base_guidance_combo = owner._make_pointer_combo(owner.base_guidance_options["rocket"])
    owner.rocket_guidance_modifiers_label = QLabel("None")
    owner.rocket_guidance_modifiers_label.setWordWrap(True)
    owner.rocket_guidance_modifiers_button = QPushButton("+")
    owner.rocket_guidance_modifiers_button.setFixedWidth(28)
    owner.rocket_guidance_modifiers_button.setToolTip("Edit ordered rocket guidance modifiers")
    owner.rocket_guidance_modifiers_button.clicked.connect(owner._edit_rocket_guidance_modifiers)
    owner.rocket_gnc_button = owner._make_section_toggle_button("rocket", "gnc")
    rocket_form.addRow("GNC", owner.rocket_gnc_button)
    owner.rocket_gnc_container = QWidget()
    rocket_gnc_form = QFormLayout(owner.rocket_gnc_container)
    rocket_gnc_form.setContentsMargins(0, 0, 0, 0)
    rocket_gnc_form.addRow("Mission Strategy", owner._make_pointer_editor_row(owner.rocket_strategy_combo, "rocket", "mission_strategy"))
    rocket_gnc_form.addRow("Mission Execution", owner._make_pointer_editor_row(owner.rocket_execution_combo, "rocket", "mission_execution"))
    rocket_gnc_form.addRow("Base Guidance", owner._make_pointer_editor_row(owner.rocket_base_guidance_combo, "rocket", "base_guidance"))
    rocket_guidance_modifiers_row = QWidget()
    rocket_guidance_modifiers_layout = QHBoxLayout(rocket_guidance_modifiers_row)
    rocket_guidance_modifiers_layout.setContentsMargins(0, 0, 0, 0)
    rocket_guidance_modifiers_layout.addWidget(owner.rocket_guidance_modifiers_label, 1)
    rocket_guidance_modifiers_layout.addWidget(owner.rocket_guidance_modifiers_button)
    rocket_gnc_form.addRow("Guidance Modifiers", rocket_guidance_modifiers_row)
    rocket_form.addRow(owner.rocket_gnc_container)
    owner.rocket_knowledge_button = owner._make_section_toggle_button("rocket", "knowledge")
    rocket_form.addRow("Knowledge / Sensor", owner.rocket_knowledge_button)
    owner.rocket_knowledge_container = owner._build_knowledge_editor("rocket")
    rocket_form.addRow(owner.rocket_knowledge_container)
    layout.addWidget(owner._wrap_object_panel(rocket_box, "Rocket"), 0, 2)
    owner._set_initial_state_section_visible("target", False)
    owner._set_initial_state_section_visible("chaser", False)
    owner._set_initial_state_section_visible("rocket", False)
    owner._set_object_section_visible("target", "gnc", False)
    owner._set_object_section_visible("chaser", "gnc", False)
    owner._set_object_section_visible("rocket", "gnc", False)
    owner._set_object_section_visible("target", "knowledge", False)
    owner._set_object_section_visible("chaser", "knowledge", False)
    owner._set_object_section_visible("rocket", "knowledge", False)
    return tab


def build_outputs_tab(owner) -> QWidget:
    tab = QWidget()
    layout = QVBoxLayout(tab)
    owner.outputs_mode_label = QLabel("")
    owner.outputs_mode_label.setWordWrap(True)
    layout.addWidget(owner.outputs_mode_label)

    owner.outputs_stack = QStackedWidget()
    layout.addWidget(owner.outputs_stack, 1)

    single_run_page = QWidget()
    single_run_layout = QVBoxLayout(single_run_page)
    single_run_layout.setContentsMargins(0, 0, 0, 0)
    single_run_layout.setSpacing(8)
    owner.stats_enabled = QCheckBox("Enable Stats")
    owner.stats_print_summary = QCheckBox("Print Summary")
    owner.stats_save_json = QCheckBox("Save JSON")
    owner.stats_save_csv = QCheckBox("Save CSV")
    owner.plots_enabled = QCheckBox("Enable Plots")
    owner.plots_dpi = QSpinBox()
    owner.plots_dpi.setRange(50, 2000)
    owner.reference_object_edit = QLineEdit()
    owner.figure_id_checks = {}
    figure_ids_widget = QWidget()
    figure_ids_layout = QGridLayout(figure_ids_widget)
    figure_ids_layout.setContentsMargins(0, 0, 0, 0)
    for idx, figure_id in enumerate(owner.figure_id_options):
        check = QCheckBox(figure_id)
        owner.figure_id_checks[figure_id] = check
        figure_ids_layout.addWidget(check, idx // 3, idx % 3)
    figure_ids_scroll = QScrollArea()
    figure_ids_scroll.setWidgetResizable(True)
    figure_ids_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    figure_ids_scroll.setWidget(figure_ids_widget)
    figure_ids_scroll.setMaximumHeight(140)
    figure_ids_panel = QWidget()
    figure_ids_panel_layout = QVBoxLayout(figure_ids_panel)
    figure_ids_panel_layout.setContentsMargins(0, 0, 0, 0)
    figure_ids_panel_layout.setSpacing(4)
    figure_ids_header = QHBoxLayout()
    figure_ids_header.setContentsMargins(0, 0, 0, 0)
    figure_ids_header.addWidget(QLabel("Figure IDs"))
    figure_ids_header.addStretch(1)
    plot_dpi_widget = QWidget()
    plot_dpi_layout = QVBoxLayout(plot_dpi_widget)
    plot_dpi_layout.setContentsMargins(0, 0, 0, 0)
    plot_dpi_layout.setSpacing(4)
    plot_dpi_layout.addWidget(QLabel("Plot DPI"))
    plot_dpi_layout.addWidget(owner.plots_dpi)
    plot_dpi_layout.addStretch(1)
    figure_ids_header.addWidget(plot_dpi_widget)
    figure_ids_panel_layout.addLayout(figure_ids_header)
    figure_ids_panel_layout.addWidget(figure_ids_scroll, 1)
    owner.animation_type_checks = {}
    animation_types_widget = QWidget()
    animation_types_layout = QGridLayout(animation_types_widget)
    animation_types_layout.setContentsMargins(0, 0, 0, 0)
    for idx, anim_type in enumerate(owner.animation_type_options):
        check = QCheckBox(anim_type)
        owner.animation_type_checks[anim_type] = check
        animation_types_layout.addWidget(check, idx // 2, idx % 2)
    animation_types_scroll = QScrollArea()
    animation_types_scroll.setWidgetResizable(True)
    animation_types_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    animation_types_scroll.setWidget(animation_types_widget)
    animation_types_scroll.setMaximumHeight(140)
    owner.animation_fps_spin = QDoubleSpinBox()
    owner.animation_fps_spin.setRange(1.0, 240.0)
    owner.animation_fps_spin.setDecimals(1)
    owner.animation_fps_spin.setValue(30.0)
    owner.animation_speed_multiple_spin = QDoubleSpinBox()
    owner.animation_speed_multiple_spin.setRange(0.1, 1000.0)
    owner.animation_speed_multiple_spin.setDecimals(2)
    owner.animation_speed_multiple_spin.setValue(10.0)
    owner.animation_frame_stride_spin = QSpinBox()
    owner.animation_frame_stride_spin.setRange(1, 100000)
    owner.animation_frame_stride_spin.setValue(1)
    left_controls = QWidget()
    left_controls_layout = QVBoxLayout(left_controls)
    left_controls_layout.setContentsMargins(0, 0, 0, 0)
    left_controls_layout.setSpacing(4)
    left_controls_layout.addWidget(owner.stats_enabled)
    left_controls_layout.addWidget(owner.stats_print_summary)
    left_controls_layout.addWidget(owner.stats_save_json)
    left_controls_layout.addWidget(owner.stats_save_csv)
    left_controls_layout.addWidget(owner.plots_enabled)
    left_controls_layout.addWidget(figure_ids_panel)
    single_run_layout.addWidget(left_controls, 0, Qt.AlignTop)

    lower_fields = QWidget()
    lower_fields_layout = QVBoxLayout(lower_fields)
    lower_fields_layout.setContentsMargins(0, 0, 0, 0)
    lower_fields_layout.setSpacing(6)
    lower_fields_layout.addWidget(QLabel("RIC Reference Object"))
    lower_fields_layout.addWidget(owner.reference_object_edit, 0, Qt.AlignLeft)
    animation_row = QHBoxLayout()
    animation_row.setContentsMargins(0, 0, 0, 0)
    animation_row.setSpacing(12)
    animation_left = QWidget()
    animation_left_layout = QVBoxLayout(animation_left)
    animation_left_layout.setContentsMargins(0, 0, 0, 0)
    animation_left_layout.setSpacing(6)
    animation_left_layout.addWidget(QLabel("Animation Types"))
    animation_left_layout.addWidget(animation_types_scroll, 0, Qt.AlignLeft)
    animation_settings_form = QFormLayout()
    animation_settings_form.addRow("Animation FPS", owner.animation_fps_spin)
    animation_settings_form.addRow("Speed Multiple", owner.animation_speed_multiple_spin)
    animation_settings_form.addRow("Frame Stride", owner.animation_frame_stride_spin)
    animation_row.addWidget(animation_left, 0, Qt.AlignTop)
    animation_row.addLayout(animation_settings_form)
    animation_row.addStretch(1)
    lower_fields_layout.addLayout(animation_row)
    single_run_layout.addWidget(lower_fields, 0, Qt.AlignLeft)
    single_run_layout.addStretch(1)
    owner.outputs_stack.addWidget(single_run_page)

    mc_page = QWidget()
    mc_layout = QFormLayout(mc_page)
    owner.mc_save_iteration_summaries = QCheckBox("Save Iteration Summaries")
    owner.mc_save_aggregate_summary = QCheckBox("Save Aggregate Summary")
    owner.mc_save_histograms = QCheckBox("Save Histograms")
    owner.mc_display_histograms = QCheckBox("Display Histograms")
    owner.mc_save_ops_dashboard = QCheckBox("Save Ops Dashboard")
    owner.mc_display_ops_dashboard = QCheckBox("Display Ops Dashboard")
    owner.mc_save_raw_runs = QCheckBox("Save Raw Runs")
    owner.mc_require_rocket_insertion = QCheckBox("Require Rocket Insertion For Pass")
    owner.mc_baseline_summary_json = QLineEdit()
    owner.mc_gate_min_closest_approach = owner._make_free_spinbox()
    owner.mc_gate_max_duration = owner._make_free_spinbox()
    owner.mc_gate_max_total_dv = owner._make_free_spinbox()
    owner.mc_gate_max_guardrail_events = owner._make_free_spinbox()
    mc_layout.addRow(owner.mc_save_iteration_summaries)
    mc_layout.addRow(owner.mc_save_aggregate_summary)
    mc_layout.addRow(owner.mc_save_histograms)
    mc_layout.addRow(owner.mc_display_histograms)
    mc_layout.addRow(owner.mc_save_ops_dashboard)
    mc_layout.addRow(owner.mc_display_ops_dashboard)
    mc_layout.addRow(owner.mc_save_raw_runs)
    mc_layout.addRow(owner.mc_require_rocket_insertion)
    mc_layout.addRow("Baseline Summary JSON", owner.mc_baseline_summary_json)
    mc_layout.addRow("Gate: Min Closest Approach (km)", owner.mc_gate_min_closest_approach)
    mc_layout.addRow("Gate: Max Duration (s)", owner.mc_gate_max_duration)
    mc_layout.addRow("Gate: Max Total dV (m/s)", owner.mc_gate_max_total_dv)
    mc_layout.addRow("Gate: Max Guardrail Events", owner.mc_gate_max_guardrail_events)
    owner.outputs_stack.addWidget(mc_page)
    return tab


def build_yaml_tab(owner) -> QWidget:
    tab = QWidget()
    layout = QVBoxLayout(tab)
    buttons = QHBoxLayout()
    owner.refresh_yaml_button = QPushButton("Refresh From Form")
    owner.refresh_yaml_button.clicked.connect(owner._refresh_yaml)
    buttons.addWidget(owner.refresh_yaml_button)
    owner.apply_yaml_button = QPushButton("Apply YAML To Form")
    owner.apply_yaml_button.clicked.connect(owner._apply_yaml_to_form)
    buttons.addWidget(owner.apply_yaml_button)
    owner.validate_yaml_button = QPushButton("Validate YAML")
    owner.validate_yaml_button.clicked.connect(owner._validate_yaml)
    buttons.addWidget(owner.validate_yaml_button)
    buttons.addStretch(1)
    layout.addLayout(buttons)
    owner.yaml_editor = QPlainTextEdit()
    layout.addWidget(owner.yaml_editor, 1)
    return tab


def build_results_tab(owner) -> QWidget:
    tab = QWidget()
    layout = QVBoxLayout(tab)

    owner.results_tabs = QTabWidget()
    layout.addWidget(owner.results_tabs, 1)

    console_tab = QWidget()
    console_layout = QVBoxLayout(console_tab)
    owner.console = QPlainTextEdit()
    owner.console.setReadOnly(True)
    console_layout.addWidget(owner.console)
    owner.results_tabs.addTab(console_tab, "Console")

    summary_tab = QWidget()
    summary_layout = QVBoxLayout(summary_tab)
    owner.results_summary = QPlainTextEdit()
    owner.results_summary.setReadOnly(True)
    summary_layout.addWidget(owner.results_summary)
    owner.results_tabs.addTab(summary_tab, "Summary")

    artifacts_tab = QWidget()
    artifacts_layout = QGridLayout(artifacts_tab)
    owner.output_files = QListWidget()
    owner.output_files.currentTextChanged.connect(owner._on_output_file_selected)
    artifacts_layout.addWidget(QLabel("Output Files"), 0, 0)
    artifacts_layout.addWidget(owner.output_files, 1, 0)

    owner.preview_title = QLabel("Select an artifact to preview.")
    artifacts_layout.addWidget(owner.preview_title, 0, 1)

    owner.preview_stack = QTabWidget()
    owner.preview_image = QLabel("No image selected.")
    owner.preview_image.setAlignment(Qt.AlignCenter)
    owner.preview_image.setMinimumSize(320, 240)
    owner.preview_image.installEventFilter(owner)
    preview_controls = QWidget()
    preview_controls_layout = QHBoxLayout(preview_controls)
    preview_controls_layout.setContentsMargins(0, 0, 0, 0)
    owner.zoom_out_button = QPushButton("Zoom -")
    owner.zoom_out_button.clicked.connect(owner._zoom_out_preview)
    preview_controls_layout.addWidget(owner.zoom_out_button)
    owner.zoom_in_button = QPushButton("Zoom +")
    owner.zoom_in_button.clicked.connect(owner._zoom_in_preview)
    preview_controls_layout.addWidget(owner.zoom_in_button)
    owner.zoom_fit_button = QPushButton("Fit")
    owner.zoom_fit_button.clicked.connect(owner._fit_preview_image)
    preview_controls_layout.addWidget(owner.zoom_fit_button)
    owner.zoom_actual_button = QPushButton("1:1")
    owner.zoom_actual_button.clicked.connect(owner._actual_size_preview)
    preview_controls_layout.addWidget(owner.zoom_actual_button)
    owner.zoom_label = QLabel("Fit")
    preview_controls_layout.addWidget(owner.zoom_label)
    preview_controls_layout.addStretch(1)
    owner.preview_scroll = QScrollArea()
    owner.preview_scroll.setWidgetResizable(False)
    owner.preview_scroll.setWidget(owner.preview_image)
    owner.preview_scroll.viewport().installEventFilter(owner)
    owner.preview_text = QPlainTextEdit()
    owner.preview_text.setReadOnly(True)
    image_tab = QWidget()
    image_layout = QVBoxLayout(image_tab)
    image_layout.addWidget(preview_controls)
    image_layout.addWidget(owner.preview_scroll, 1)
    owner.preview_stack.addTab(image_tab, "Image")
    owner.preview_stack.addTab(owner.preview_text, "Text")
    artifacts_layout.addWidget(owner.preview_stack, 1, 1)
    artifacts_layout.setColumnStretch(0, 2)
    artifacts_layout.setColumnStretch(1, 3)
    owner.results_tabs.addTab(artifacts_tab, "Artifacts")
    owner.preview_image.setPixmap(QPixmap())
    return tab
